[versions]
appcompat = "1.8.0"
gradle = "9.3.1"
material = "1.14.0"

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "gradle" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "gradle" }
