// All-WebViewTester
// module build.gradle
plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace = "com.landenlabs.all_webviewtester"
    compileSdk = 37

    defaultConfig {
        applicationId = "com.landenlabs.all_webviewtester"
        minSdk = 23
        targetSdk = 34

        versionCode = 100128
        versionName = "13.01.05"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"

        // Save app version in string so resource can be used in layouts
        resValue "string", "versionName", "version " + versionName
    }

    buildFeatures {
        buildConfig = true
        resValues = true
    }

    buildTypes {
        release {
            minifyEnabled = false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    lint {
        abortOnError = false
        disable += ['DefaultLocale', 'SimpleDateFormat', 'InflateParams', 'SpUsage', 'UseCompoundDrawables', 'HandlerLeak', 'ViewConstructor', 'SetTextI18n', 'RtlSymmetry', 'RtlHardcoded', 'ContentDescription', 'MissingTranslation', 'ValidFragment', 'UnusedAttribute', 'FieldCanBeLocal', 'LocalSuppress', 'HardcodedText', 'Typos']
    }

    tasks.withType(JavaCompile).configureEach {
        // Enable verbose lint reporting during build.
        options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
    }
}

dependencies {
    implementation libs.androidx.appcompat
    implementation libs.material
}

// Rename app
androidComponents {
    onVariants(selector().all()) { variant ->
        def ourName = project.parent.name
        variant.outputs.forEach { output ->
            def versionStr = output.versionName.get()
            def outFileName = "${ourName}-${variant.name}-${versionStr}.apk"
            output.outputFileName.set(outFileName)
            println "out name= ${outFileName}"
        }
    }
}
